### ISSUE TITLE
Design system

### ISSUE THREAD

**Issue by gcstaublin** [gcstaublin/pregame#13]
As we begin writing CSS, are there design system changes or documentation that should happen?
- [ ] Grid System
- [ ] Vertical Rhythm 
- [ ] Add things here

**Comment by mfouquet** [comment]
Grid: Here's a link to the grid I came up with based on that one grid system we liked at one point. It's currently in the docs repo here - let me know your thoughts: https://github.com/hudl/kickoff-docs/blob/master/assets/css/base/_grid.scss

Vertical rhythm: I've messed around with putting together a typographic scale that makes the vertical rhythm pretty simple through some basic mixins. Let me know what you think:

```scss
$font-size: 1rem; // 16px
$line-height: $font-size * 1.2;

$type-scale: (
  -1: 0.75rem,
  0: 1rem,
  1: 1.333rem,
  2: 1.777rem,
  3: 2.369rem
);

@function type-scale($level) {
  @return map-get($type-scale, $level);
}


$line-heights: (
  -1: $line-height,
  0: $line-height,
  1: $line-height * 2,
  2: $line-height * 2,
  3: $line-height * 3
);

@function line-height($level) {
  @return map-get($line-heights, $level);
}

@mixin type-setting($level: 0) {
  font-size: type-scale($level);
  line-height: line-height($level);
}
```

This was taken from an article I can't seem to find anymore but the idea here is that you can input any typographic scale we decide on (I think what we have in kickoff might be a perfect fourth like above) and then determine the line-height for each typographic element from there (a multiple of the base line-height essentially that's at least bigger than the font-size). Our vertical rhythm for things that are not text (like buttons) can also be derived from that base line-height multiplied by 2,3,whatever as necessary. This takes a lot of the thinking out of sizing - if you just want base text, don't do anything, if you're doing headers you do @include type-setting(1), etc.

If we push to have other sizing determined based on that base font size and line height (i.e., use 0.5, 1, 1.5, etc.) this should make for a pretty nice setup and keep things well spaced. Or we can just use something like this: http://www.gridlover.net/app/
